name: Feature request
description: File a feature request
title: "[New feature]: "
labels: ["feature"]
projects: ["wnetking/redmine-extends"]
assignees:
  - wnetking
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to add a new feature request!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please, describe you feature. 
    validations:
      required: true
